# Generated by Django 2.1.7 on 2019-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
